import { escapeHtml, graph, json, owner, validEmail, BUSINESS_TIME_ZONE } from '../_shared/calendar.js';
const CONTACT_URL='https://www.sherbornecmc.com/#contact', CONFIRMATION_TEXT='Thank you, we will respond to your request shortly.\n\nBest wishes,\nYour Sherborne Team\n\nIf you need to cancel, please contact us.';
function clean(s,max=500){return String(s||'').trim().slice(0,max)}
function htmlLines(s){return escapeHtml(s).replaceAll('\n','<br>')}
function formatNowInZone(timeZone){return new Date().toLocaleString('en-GB',{timeZone,weekday:'long',day:'numeric',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit',timeZoneName:'short'})}
function contactError(message,status=500){return json({error:message,contactUrl:CONTACT_URL},status)}
function block(label,value){return `<p><strong>${escapeHtml(label)}</strong><br>${escapeHtml(value||'').replaceAll('\n','<br>')}</p>`}
function zoneSummary(clientTimeZone){return clientTimeZone&&clientTimeZone!==BUSINESS_TIME_ZONE?`Visitor timezone: ${escapeHtml(clientTimeZone)}<br>Sherborne diary timezone: ${escapeHtml(BUSINESS_TIME_ZONE)}<br>Reference now: ${escapeHtml(formatNowInZone(clientTimeZone))} (Sherborne diary time: ${escapeHtml(formatNowInZone(BUSINESS_TIME_ZONE))})`:`Visitor timezone: ${escapeHtml(clientTimeZone||BUSINESS_TIME_ZONE)}<br>Sherborne diary timezone: ${escapeHtml(BUSINESS_TIME_ZONE)}`}
export async function onRequestPost({request,env}){try{const body=await request.json(), pathway=String(body.pathway||'')==='client'?'Client session pathway':String(body.pathway||'')==='intro'?'Introductory pathway':'Not selected', name=clean(body.name,120), email=clean(body.email,254), phone=clean(body.phone,60), message=clean(body.message,250), preferredTimes=clean(body.preferredTimes,500), location=clean(body.location,160), assistantEmail=clean(body.otherEmail,254), clientTimeZone=clean(body.clientTimeZone,80);if(!name||!validEmail(email)||!phone||phone.length<7||!message||!preferredTimes||!location)return json({error:'Please complete the required details and try again.'},400);if(assistantEmail&&!validEmail(assistantEmail))return json({error:'Please check the assistant email address.'},400);const michael=owner(env), internalBody=`<div style="font-family:Arial,sans-serif;line-height:1.45;color:#17201c"><h2 style="font-family:Georgia,serif;font-weight:400;color:#36463b">Alternative time request</h2>${block('Pathway',pathway)}${block('Name',name)}${block('Email',email)}${block('Phone',phone)}${block('Location / time zone',location)}<p><strong>Time zone</strong><br>${zoneSummary(clientTimeZone)}</p>${block('Suggested contact times',preferredTimes)}${block('What would be helpful to explore',message)}${assistantEmail?block('Assistant copied',assistantEmail):''}</div>`;await graph(env,`/users/${encodeURIComponent(michael)}/sendMail`,'POST',{message:{subject:'Alternative time request - Sherborne session',body:{contentType:'HTML',content:internalBody},toRecipients:[{emailAddress:{address:michael}}]},saveToSentItems:true});const cc=assistantEmail?[{emailAddress:{address:assistantEmail}}]:[];await graph(env,`/users/${encodeURIComponent(michael)}/sendMail`,'POST',{message:{subject:'Your request has been received',body:{contentType:'HTML',content:htmlLines(CONFIRMATION_TEXT)},toRecipients:[{emailAddress:{address:email}}],ccRecipients:cc},saveToSentItems:true});return json({ok:true})}catch(e){console.log('Alternative request error',{endpoint:'/api/alternative',message:e.message});return contactError('Sorry, we could not send your request just now. Please try again, or contact Sherborne directly.',500)}}
