import { escapeHtml, graph, json, owner, validEmail, BUSINESS_TIME_ZONE } from '../_shared/calendar.js';
const CONTACT_URL='https://www.sherbornecmc.com/#contact';
function isExisting(t){ return t === 'existing'; }
function confirmationText(clientType){return `Thank you for your request, we will respond shortly.${isExisting(clientType)?'\n\nPlease note that sessions changed or cancelled within 48 hours of the scheduled time remain chargeable.':''}\n\nBest wishes,\nYour Sherborne Team\n\nIf you need to cancel, please contact us.`;}
function htmlLines(s){ return escapeHtml(s).replaceAll('\n','<br>'); }
function formatNowInZone(timeZone){return new Date().toLocaleString('en-GB',{timeZone,weekday:'long',day:'numeric',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit',timeZoneName:'short'});}
function contactError(message,status=500){return json({error:message,contactUrl:CONTACT_URL},status);}
function zoneSummary(clientTimeZone){return clientTimeZone&&clientTimeZone!==BUSINESS_TIME_ZONE?`Visitor timezone: ${escapeHtml(clientTimeZone)}<br>Sherborne diary timezone: ${escapeHtml(BUSINESS_TIME_ZONE)}<br>Reference now: ${escapeHtml(formatNowInZone(clientTimeZone))} (Sherborne diary time: ${escapeHtml(formatNowInZone(BUSINESS_TIME_ZONE))})`:`Visitor timezone: ${escapeHtml(clientTimeZone||BUSINESS_TIME_ZONE)}<br>Sherborne diary timezone: ${escapeHtml(BUSINESS_TIME_ZONE)}`;}
function altSubject(clientType){return isExisting(clientType)?'Request for alternative time slot':'Request for alternative time slot - introductory consultation';}
export async function onRequestPost({request,env}){try{const body=await request.json();const{name,email,phone,message,preferredTimes,location,otherEmail,clientTimeZone}=body;const clientType=isExisting(body.clientType)?'existing':'new';const assistantEmail=String(otherEmail||'').trim();if(!name||!validEmail(email)||!phone||phone.length<7||!message||!preferredTimes||!location)return json({error:'Please complete the required details and try again.'},400);if(assistantEmail&&!validEmail(assistantEmail))return json({error:'Please check the assistant email address.'},400);const michael=owner(env);await graph(env,`/users/${encodeURIComponent(michael)}/sendMail`,'POST',{message:{subject:altSubject(clientType),body:{contentType:'HTML',content:`<p>New alternative time request received.</p><p><strong>Request type:</strong><br>${clientType==='existing'?'Session':'Introductory consultation'}</p><p><strong>Name:</strong><br>${escapeHtml(name)}</p><p><strong>Email:</strong><br>${escapeHtml(email)}</p><p><strong>Phone:</strong><br>${escapeHtml(phone)}</p><p><strong>Location / time zone:</strong><br>${escapeHtml(location)}</p><p><strong>Time zone:</strong><br>${zoneSummary(clientTimeZone)}</p><p><strong>Suggested contact times:</strong><br>${escapeHtml(preferredTimes).replaceAll('\n','<br>')}</p><p><strong>What would be helpful to explore:</strong><br>${escapeHtml(message).replaceAll('\n','<br>')}</p>${assistantEmail?`<p><strong>Assistant copied:</strong><br>${escapeHtml(assistantEmail)}</p>`:''}`},toRecipients:[{emailAddress:{address:michael}}]},saveToSentItems:true});const cc=assistantEmail?[{emailAddress:{address:assistantEmail}}]:[];await graph(env,`/users/${encodeURIComponent(michael)}/sendMail`,'POST',{message:{subject:'Your request has been received',body:{contentType:'HTML',content:`<p>${htmlLines(confirmationText(clientType))}</p>`},toRecipients:[{emailAddress:{address:email}}],ccRecipients:cc},saveToSentItems:true});return json({ok:true});}catch(e){console.log('Alternative request error',{endpoint:'/api/alternative',message:e.message});return contactError('Sorry, we could not send your request just now. Please try again, or contact Sherborne directly.',500);}}
